### ISSUE TITLE
Reverse gentoo mp4v2 patch and look at applying improved patch

### ISSUE THREAD

**Issue by ghost** [stsquad/easytag#3]
I noticed on http://sourceforge.net/tracker/?func=detail&aid=2458661&group_id=5216&atid=305216 that there is a better patch for the configure.in and related mp4 source code to retain compilation against older libmp4v2 libraries whilst also adding support for the newer one (that has different header names). It also seems to extend this to also include some API changes, so we may want to investigate if those are actually needed or not (perhaps they are for mp4v2 >= 2.0, but not needed for mp4v2 == 1.9)

**Comment by stsquad** [comment]
Housekeeping. Fixed in cddc6f279a153006b382db0dee1c4115b16335d7
