### ISSUE TITLE
Makefile.am includes missing debian/ path in distfiles

### ISSUE THREAD

**Issue by ferdnyc** [stsquad/easytag#6]
The current git source is broken for "make dist-bzip2" (or any other form that uses the distdir target), because it attempts to include the nonexistent debian directory as part of the EXTRA_DIST files. This patch corrects, and results in successful distfile creation.

http://dl.dropbox.com/u/1031979/0001-Exclude-nonexistent-debian-path-from-EXTRA_DIST.patch

**Comment by stsquad** [comment]
Applied.

Thanks for your patch.
