### ISSUE TITLE
Please, tag the releases

### ISSUE THREAD

**Issue by rbrito** [stsquad/easytag#7]
For ease of reference, it would be nice if you could tag the releases that the old upstream generated some time ago.

Thanks, Rogério Brito.

**Comment by stsquad** [comment]
All the commits are on top of each however I did tag them when I did the original import. git however doesn't automatically push them. I have pushed them now.

**Comment by rbrito** [comment]
Thanks also.

Now it seems we have two sets of tags, but that's OK.
